qcacmn: Initialize whole char array elements
Initialize whole char array elements instead of initializing
just the first element in an array.

Fixed below compiler optimization error:
error: suggest braces around initialization of subobject.
[-Werror,-Wmissing-braces]

Change-Id: I103d95274e654cb7d232775cf7986a772741a152
CRs-Fixed: 3357183